# Extract the LaLonde dataset 

We want to extract the LaLonde data set that has been used to generate all the other realcause datasets in the `realcause_datasets` folder. This is the same base data set that we will use to train the Credence model.

In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [17]:
import pandas as pd
import numpy as np
from numpy.testing import assert_approx_equal
from pathlib import Path
import time

from loading import load_from_folder

from data.lalonde import load_lalonde
from data.twins import load_twins
from consts import REALCAUSE_DATASETS_FOLDER, N_SAMPLE_SEEDS, N_AGG_SEEDS
import matplotlib.pyplot as plt

In [18]:
psid_gen_model, args = load_from_folder(dataset='lalonde_psid1')
# psid_w, psid_t, psid_y = load_lalonde(obs_version='psid', data_format='pandas')
d = load_lalonde(obs_version='psid', data_format='pandas')

Namespace(data='lalonde', dataroot='/home/mila/r/raghupas/causal-benchmark/datasets', saveroot='save', train=True, eval=True, overwrite_reload='', model_type='tarnet', dist='SigmoidFlow', dist_args=['ndim=2', 'base_distribution=uniform'], atoms=[0.0], n_hidden_layers=1, dim_h=4, activation='ReLU', kernel_t='RBFKernel', kernel_y='RBFKernel', var_dist='MeanFieldVariationalDistribution', num_tasks=32, lr=0.01, batch_size=25000, num_epochs=10000, early_stop=True, patience=None, ignore_w=False, grad_norm=inf, test_size=None, w_transform='Normalize', y_transform='Normalize', train_prop=0.5, val_prop=0.1, test_prop=0.4, seed=123, comet=True, num_univariate_tests=100, verbose=0, dataset_identifier=None, sample_size=500, biasing='linear', weight=1, intercept=0)
2025-11-04 12:24:49.711035 / Namespace(data='lalonde', dataroot='./datasets', saveroot='/work/pi_jensen_umass_edu/pboddavarama_umass_edu/nfl/realcause/GenModelCkpts/lalonde/psid1/save', train=False, eval=False, overwrite_reload='', model_type='tarnet', dist='SigmoidFlow', dist_args=['ndim=2', 'base_distribution=uniform'], atoms=[0.0], n_hidden_layers=1, dim_h=4, activation='ReLU', kernel_t='RBFKernel', kernel_y='RBFKernel', var_dist='MeanFieldVariationalDistribution', num_tasks=32, lr=0.01, batch_size=25000, num_epochs=10000, early_stop=True, patience=None, ignore_w=False, grad_norm=inf, test_size=None, w_transform='Normalize', y_transform='Normalize', train_prop=0.5, val_prop=0.1, test_prop=0.4, seed=123, comet=False, num_univariate_tests=100, verbose=0, dataset_identifier=None, sample_size=500, biasing='linear', weight=1, intercept=0)
2025-11-04 12:24:49.711097 / getting data: lalonde
2025-11-04 12:24:49.721040 / ate: None
2025-11-04 12:24:49.721094 / <models.distributions.distributions.MixedDistribution object at 0x7cc7d41e9600>
2025-11-04 12:24:49.721114 / {'batch_size': 25000, 'lr': 0.01, 'num_epochs': 10000, 'verbose': True, 'print_every_iters': 100, 'optim': <class 'torch.optim.adam.Adam'>, 'eval_every': 100, 'plot_every': 100, 'p_every': 100, 'optim_args': {}}
2025-11-04 12:24:49.721134 / model type: tarnet
2025-11-04 12:24:49.721189 / {'n_hidden_layers': 1, 'dim_h': 4, 'activation': ReLU()}
n_train: 1338	n_val: 268	n_test: 1069
test_idxs:  (1069,)

/work/pi_jensen_umass_edu/pboddavarama_umass_edu/nfl/realcause/loading.py:72: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dicts = torch.load(model.savepath)

In [19]:
d['y']

0        9930.045898
1        3595.894043
2       24909.449219
3        7506.145996
4         289.789886
            ...
2485    38568.664062
2486    59109.062500
2487    55710.292969
2488    20540.398438
2489    53198.156250
Name: re78, Length: 2675, dtype: float32

In [20]:
psid_gen_model.ate(noisy=True)

y: tensor([[0.1924],
        [0.7368],
        [0.2067]])
y: tensor([[7.6886e-01],
        [6.4740e-02],
        [7.0729e-01],
        [9.7365e-01],
        [3.2469e-01],
        [9.4043e-01],
        [5.3453e-01],
        [9.4597e-02],
        [4.3476e-03],
        [6.9342e-01],
        [6.8940e-01],
        [1.8697e-01],
        [8.1714e-01],
        [6.8414e-01],
        [1.2556e-01],
        [4.0967e-01],
        [2.1682e-01],
        [8.3042e-01],
        [4.0749e-01],
        [9.7182e-01],
        [5.5247e-01],
        [7.8730e-01],
        [9.2942e-01],
        [4.4948e-01],
        [3.9365e-01],
        [6.6321e-01],
        [5.0834e-01],
        [8.8531e-01],
        [4.5459e-01],
        [9.9879e-01],
        [8.2787e-01],
        [8.8852e-01],
        [4.1688e-01],
        [4.9259e-01],
        [8.7802e-01],
        [3.5203e-01],
        [8.9705e-01],
        [5.3046e-01],
        [6.9710e-01],
        [9.1575e-01],
        [8.7252e-01],
        [1.4217e-01],
        [9.3350e-01],
        [8.3130e-01],
        [1.7022e-03],
        [8.5966e-01],
        [6.4502e-01],
        [6.1120e-01],
        [7.0053e-02],
        [3.8386e-01],
        [7.8651e-01],
        [5.7182e-01],
        [7.7155e-01],
        [1.1655e-01],
        [8.2685e-01],
        [5.9642e-01],
        [7.7304e-01],
        [9.1910e-01],
        [8.1726e-01],
        [5.3555e-01],
        [6.3359e-01],
        [8.1503e-01],
        [4.6672e-01],
        [2.7239e-01],
        [8.1923e-01],
        [5.6716e-01],
        [4.5199e-01],
        [1.7360e-02],
        [3.7153e-01],
        [9.9889e-01],
        [4.2707e-01],
        [6.2772e-01],
        [7.3774e-01],
        [2.4181e-01],
        [9.0893e-01],
        [9.5941e-01],
        [4.1639e-01],
        [6.7970e-01],
        [1.0023e-01],
        [1.0548e-01],
        [5.8073e-01],
        [9.4335e-02],
        [3.3032e-01],
        [8.4448e-01],
        [9.8975e-01],
        [5.0511e-01],
        [4.4988e-01],
        [9.5203e-01],
        [5.5088e-02],
        [9.6700e-01],
        [2.8311e-01],
        [5.3026e-01],
        [4.8410e-01],
        [2.8650e-01],
        [6.8908e-01],
        [4.3590e-01],
        [5.3064e-01],
        [4.0489e-01],
        [7.1992e-01],
        [1.9140e-01],
        [1.1096e-01],
        [2.5710e-01],
        [9.9031e-01],
        [5.4649e-01],
        [6.6083e-01],
        [7.7401e-01],
        [4.1934e-01],
        [8.2437e-01],
        [8.4369e-02],
        [2.7029e-01],
        [9.2410e-01],
        [3.0948e-01],
        [1.9206e-01],
        [1.7293e-02],
        [2.1421e-02],
        [5.5972e-01],
        [1.4634e-01],
        [9.1575e-03],
        [9.7209e-01],
        [6.7882e-01],
        [8.7060e-01],
        [6.2271e-01],
        [4.1209e-01],
        [1.7267e-01],
        [2.0090e-02],
        [5.7929e-02],
        [1.2726e-02],
        [4.3834e-01],
        [5.5257e-01],
        [9.3360e-01],
        [4.0403e-01],
        [4.7380e-02],
        [1.7517e-01],
        [9.4384e-01],
        [8.5932e-01],
        [6.7491e-01],
        [1.5627e-01],
        [5.8208e-01],
        [2.8433e-01],
        [7.4660e-01],
        [6.3203e-01],
        [8.2645e-01],
        [4.3602e-01],
        [9.9630e-01],
        [6.3213e-01],
        [8.8964e-01],
        [5.1591e-01],
        [7.7851e-01],
        [8.5831e-01],
        [5.7472e-01],
        [9.2093e-01],
        [7.4175e-02],
        [4.4628e-01],
        [4.2138e-01],
        [4.8037e-01],
        [6.6480e-01],
        [3.7082e-01],
        [3.8646e-01],
        [8.2763e-01],
        [1.3614e-01],
        [4.6726e-01],
        [8.7022e-01],
        [9.5213e-01],
        [8.4329e-02],
        [6.5732e-01],
        [7.0615e-01],
        [5.9295e-01],
        [6.6240e-01],
        [3.0607e-01],
        [5.9109e-01],
        [6.0778e-01],
        [6.6358e-01],
        [6.0970e-01],
        [1.9896e-01],
        [5.5899e-01],
        [2.9797e-01],
        [7.9654e-01],
        [8.6823e-01],
        [2.7991e-02],
        [1.3793e-01],
        [1.9919e-01],
        [2.6232e-01],
        [7.0954e-01],
        [1.8326e-01],
        [9.6846e-01],
        [4.0615e-02],
        [2.5016e-01],
        [2.6213e-01],
        [7.8865e-01],
        [4.5067e-01],
        [6.3567e-01],
        [5.8326e-01],
        [5.7156e-01],
        [9.2970e-01],
        [3.3957e-01],
        [2.7543e-02],
        [6.6673e-01],
        [8.3104e-01],
        [1.7956e-01],
        [2.7645e-01],
        [1.9670e-01],
        [8.3421e-01],
        [4.3357e-01],
        [1.1358e-01],
        [1.3882e-01],
        [3.1601e-01],
        [5.6629e-01],
        [9.0785e-01],
        [2.1322e-02],
        [8.1476e-01],
        [3.2534e-01],
        [8.8498e-02],
        [7.3522e-02],
        [1.8123e-01],
        [1.5650e-01],
        [6.8254e-01],
        [8.2274e-01],
        [1.7663e-01],
        [9.7795e-01],
        [3.6656e-02],
        [1.9890e-01],
        [3.1425e-01],
        [3.6551e-01],
        [5.4193e-02],
        [7.1437e-01],
        [5.1790e-01],
        [9.7536e-02],
        [3.0133e-01],
        [3.0731e-02],
        [3.8989e-01],
        [6.4667e-01],
        [5.4444e-01],
        [8.0691e-01],
        [4.6082e-01],
        [4.5587e-01],
        [8.5857e-01],
        [4.1706e-02],
        [3.8407e-01],
        [6.8109e-01],
        [4.7407e-01],
        [7.1347e-01],
        [8.7061e-01],
        [6.7366e-01],
        [6.6233e-01],
        [3.3792e-01],
        [5.4206e-01],
        [8.0480e-01],
        [2.2099e-01],
        [9.1605e-01],
        [7.7513e-01],
        [1.4379e-01],
        [9.8920e-02],
        [8.9329e-01],
        [3.5725e-01],
        [5.9691e-01],
        [2.6447e-02],
        [9.2533e-02],
        [1.5759e-01],
        [1.8093e-01],
        [5.9346e-01],
        [9.6637e-01],
        [1.4418e-01],
        [8.2546e-01],
        [5.8652e-01],
        [8.7461e-01],
        [2.3040e-01],
        [2.2824e-01],
        [6.1191e-01],
        [8.4263e-01],
        [2.0494e-01],
        [6.9998e-01],
        [7.5716e-01],
        [9.7544e-01],
        [4.1438e-01],
        [8.9669e-04],
        [9.2427e-01],
        [3.1048e-01],
        [2.8257e-01],
        [6.3205e-01],
        [9.3796e-01],
        [3.9028e-01],
        [1.7585e-01],
        [2.5583e-01],
        [2.2387e-01],
        [4.4715e-02],
        [2.0921e-01],
        [6.4727e-01],
        [8.1066e-01],
        [8.8200e-01],
        [2.9518e-02],
        [1.2628e-01],
        [6.3602e-01],
        [9.1775e-01],
        [7.3274e-02],
        [5.0153e-01],
        [5.6770e-01],
        [9.0565e-01],
        [4.9651e-01],
        [5.8123e-01],
        [4.5205e-01],
        [8.6539e-01],
        [5.2787e-02],
        [3.7608e-01],
        [3.8904e-01],
        [3.4412e-01],
        [9.7020e-01],
        [5.1305e-01],
        [6.1003e-01],
        [2.8732e-01],
        [7.1701e-01],
        [7.1234e-01],
        [2.8488e-01],
        [8.7979e-01],
        [3.9254e-01],
        [7.3114e-01],
        [9.8466e-01],
        [5.1385e-01],
        [3.0784e-01],
        [7.6883e-01],
        [3.4934e-01],
        [1.5197e-01],
        [6.6549e-01],
        [6.9518e-02],
        [9.7158e-01],
        [2.7249e-01],
        [9.5713e-01],
        [1.9865e-01],
        [7.6521e-02],
        [5.0449e-01],
        [9.1816e-02],
        [5.6808e-01],
        [5.7069e-02],
        [3.7558e-01],
        [6.3647e-01],
        [2.0885e-01],
        [2.9339e-01],
        [8.6969e-01],
        [4.5446e-01],
        [5.5467e-01],
        [9.3810e-02],
        [1.7927e-02],
        [1.2033e-01],
        [3.7057e-01],
        [8.7386e-01],
        [6.9385e-01],
        [3.5553e-01],
        [4.8989e-01],
        [8.0512e-01],
        [8.4766e-01],
        [1.4777e-01],
        [1.8204e-01],
        [1.7496e-01],
        [7.9323e-01],
        [8.8203e-01],
        [2.8689e-01],
        [7.8481e-01],
        [2.5994e-01],
        [5.5020e-01],
        [9.6584e-01],
        [3.7116e-01],
        [6.8759e-01],
        [1.8011e-01],
        [1.1930e-01],
        [8.3152e-01],
        [1.9446e-01],
        [2.6272e-01],
        [8.9370e-01],
        [8.5832e-01],
        [7.4194e-01],
        [2.6396e-01],
        [2.3738e-01],
        [4.9221e-01],
        [9.3119e-01],
        [6.7019e-01],
        [8.3479e-01],
        [8.1348e-01],
        [2.6116e-01],
        [8.7734e-01],
        [2.1414e-01],
        [1.5586e-02],
        [7.1236e-01],
        [8.2180e-03],
        [6.6385e-01],
        [5.3805e-01],
        [2.6576e-01],
        [5.1837e-01],
        [3.4789e-01],
        [9.8513e-01],
        [2.0559e-01],
        [2.7868e-01],
        [1.1422e-02],
        [2.9913e-01],
        [2.7468e-02],
        [8.1166e-01],
        [7.7712e-01],
        [9.3011e-01],
        [4.9180e-02],
        [5.9471e-01],
        [1.6672e-01],
        [7.9658e-01],
        [1.0329e-01],
        [1.2006e-01],
        [2.5565e-01],
        [8.6436e-01],
        [8.9386e-01],
        [2.0586e-01],
        [7.6353e-01],
        [8.1086e-01],
        [6.2284e-01],
        [1.7141e-01],
        [3.2066e-01],
        [6.0177e-01],
        [7.0318e-01],
        [9.9889e-01],
        [4.2742e-01],
        [5.1123e-01],
        [3.3643e-01],
        [8.5737e-01],
        [1.2773e-02],
        [8.2649e-01],
        [2.0774e-01],
        [4.8078e-01],
        [5.9679e-01],
        [8.9364e-01],
        [3.4340e-01],
        [4.8963e-01],
        [5.6901e-01],
        [8.7220e-01],
        [2.7615e-01],
        [5.1227e-01],
        [1.4514e-01],
        [8.4805e-01],
        [1.0398e-01],
        [4.6662e-01],
        [5.4384e-01],
        [3.3335e-01],
        [9.2158e-01],
        [1.2803e-01],
        [8.4670e-01],
        [6.6754e-01],
        [5.9281e-01],
        [6.2324e-01],
        [5.2106e-01],
        [4.9970e-01],
        [1.1569e-01],
        [1.0253e-01],
        [8.0608e-01],
        [6.0844e-01],
        [6.5933e-01],
        [2.0383e-01],
        [4.9145e-01],
        [4.9477e-01],
        [1.4760e-01],
        [4.6506e-01],
        [4.3755e-01],
        [1.4782e-01],
        [6.9990e-01],
        [1.1505e-01],
        [4.7924e-02],
        [7.9499e-02],
        [5.4870e-01],
        [3.6431e-01],
        [4.4368e-01],
        [8.6224e-01],
        [8.0536e-01],
        [2.3515e-01],
        [4.9156e-01],
        [1.1198e-01],
        [1.6794e-01],
        [5.1857e-02],
        [6.5576e-01],
        [1.2781e-01],
        [8.6644e-01],
        [4.4830e-01],
        [8.8736e-02],
        [2.7199e-01],
        [9.0008e-01],
        [4.3069e-01],
        [1.6469e-01],
        [2.3023e-01],
        [7.9144e-01],
        [1.4411e-01],
        [5.4874e-01],
        [9.5499e-01],
        [5.8710e-01],
        [3.1180e-01],
        [9.1049e-01],
        [2.7467e-01],
        [4.5461e-01],
        [5.3444e-01],
        [5.6501e-01],
        [6.0805e-01],
        [8.6873e-01],
        [4.4317e-01],
        [3.1687e-01],
        [6.7954e-01],
        [2.1915e-02],
        [4.7824e-01],
        [4.9946e-01],
        [2.1339e-01],
        [5.7611e-01],
        [7.5790e-01],
        [6.3255e-01],
        [1.2652e-01],
        [3.0689e-01],
        [5.9413e-01],
        [5.1223e-02],
        [6.1728e-01],
        [8.5125e-01],
        [1.3844e-01],
        [7.8040e-02],
        [5.4409e-01],
        [4.0903e-02],
        [8.9658e-01],
        [1.5342e-01],
        [6.4400e-01],
        [9.3412e-01],
        [3.0165e-01],
        [8.4206e-01],
        [3.2238e-01],
        [3.1130e-02],
        [2.4241e-03],
        [1.9720e-01],
        [5.2999e-01],
        [2.0812e-01],
        [4.1747e-01],
        [1.7859e-01],
        [7.8894e-01],
        [2.1463e-02],
        [1.1099e-01]])
y: tensor([], size=(0, 1))

RuntimeError: cannot reshape tensor of 0 elements into shape [0, 1, -1] because the unspecified dimension size -1 can be any value and is ambiguous

In [8]:
psid_gen_model.ate(noisy=False)

/work/pi_jensen_umass_edu/pboddavarama_umass_edu/nfl/realcause/models/distributions/distributions.py:275: UserWarning: mean not implemented for <models.distributions.distributions.SigmoidFlow object at 0x7cc8165a77c0> ndim:2 base_distribution:uniform
  warnings.warn(f'mean not implemented for {self.__str__()}')

np.float32(-0.07012261)

In [9]:
psid_gen_model

This is the dataset that has been used to generate the `lalonde_psid` datasets with realcause. We will now store and use this dataset for Credence.

In [11]:
# Store the lalonde psid data set here. 

# Join the psid_w, psid_t, psid_y dataframes into a single dataframe
psid = pd.concat([d['w'], d['t'], d['y']], axis=1)
# psid.to_csv('pba_data/psid.csv', index=False)

In [13]:
# Testing the realcause package for basic functionality
from loading import load_realcause_dataset

df = load_realcause_dataset('lalonde_psid', 1)

FileNotFoundError: [Errno 2] No such file or directory: '/work/pi_jensen_umass_edu/pboddavarama_umass_edu/nfl/realcause/nfl_datasets/lalonde_psid_sample1.csv'

In [35]:
df

NameError: name 'df' is not defined

In [36]:
df.shape

NameError: name 'df' is not defined

In [10]:
df.columns

Index(['age', 'education', 'black', 'hispanic', 'married', 'nodegree', 're74',
       're75', 't', 'y', 'y0', 'y1', 'ite'],
      dtype='object')

In [2]:
# Extract the twins dataset 
d = load_twins(dataroot='datasets')

Twins dataset already exists at datasets/twins.csv

In [7]:
df = pd.read_csv('datasets/twins.csv', index_col=0)

In [8]:
df.head()

,eclamp,gestatcat1,gestatcat2,gestatcat3,gestatcat4,gestatcat5,gestatcat6,gestatcat7,gestatcat8,gestatcat9,...,crace,birmon,dtotord_min,dlivord_min,T,y0,y1,yf,y_cf,Propensity
0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,3.0,3.0,0,0.0,0.0,0.0,0.0,0.638284
1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,1,0.0,1.0,1.0,0.0,0.587705
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0,0.0,0.0,0.0,0.0,0.802878
3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,2.0,2.0,1,0.0,0.0,0.0,0.0,0.741004
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,3.0,1,0.0,0.0,0.0,0.0,0.616016

In [11]:
# Base dataset for twins.csv
base_twins = pd.read_csv('base_datasets/twins.csv')

In [12]:
base_twins.head()

,eclamp,gestatcat1,gestatcat2,gestatcat3,gestatcat4,gestatcat5,gestatcat6,gestatcat7,gestatcat8,gestatcat9,...,feduc6,dfageq,nprevistq,data_year,crace,birmon,dtotord_min,dlivord_min,t,y
0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,3.0,3.0,0,0.0
1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,5.0,8.0,0.0,0.0,0.0,0.0,1.0,1.0,1,1.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,4.0,6.0,0.0,0.0,0.0,0.0,2.0,2.0,1,0.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,7.0,0.0,0.0,1.0,0.0,3.0,3.0,1,0.0

In [20]:
# Find the proportion of t = 0 and t = 1 in the base dataset
base_twins['t'].value_counts() / len(base_twins)

1    0.745661
0    0.254339
Name: t, dtype: float64

In [21]:
# See which columns are in the twins dataset which are continuous and which are categorical
base_twins.dtypes

eclamp         float64
gestatcat1     float64
gestatcat2     float64
gestatcat3     float64
gestatcat4     float64
                ...
birmon         float64
dtotord_min    float64
dlivord_min    float64
t                int64
y              float64
Length: 77, dtype: object

In [22]:
for col in base_twins.columns:
    print(col)
    print(base_twins[col].unique())
    print('--------------------------------')

eclamp
[0. 1.]
--------------------------------
gestatcat1
[0. 1.]
--------------------------------
gestatcat2
[1. 0.]
--------------------------------
gestatcat3
[1. 0.]
--------------------------------
gestatcat4
[0. 1.]
--------------------------------
gestatcat5
[1. 0.]
--------------------------------
gestatcat6
[1. 0.]
--------------------------------
gestatcat7
[0. 1.]
--------------------------------
gestatcat8
[0. 1.]
--------------------------------
gestatcat9
[1. 0.]
--------------------------------
gestatcat10
[0. 1.]
--------------------------------
gestatcat1.1
[0. 1.]
--------------------------------
gestatcat2.1
[1. 0.]
--------------------------------
gestatcat3.1
[1. 0.]
--------------------------------
bord
[1. 0.]
--------------------------------
gestatcat4.1
[1. 0.]
--------------------------------
gestatcat6.1
[1. 0.]
--------------------------------
gestatcat7.1
[1. 0.]
--------------------------------
gestatcat8.1
[1. 0.]
--------------------------------
gestatcat9.1
[0. 1.]
--------------------------------
gestatcat10.1
[0. 1.]
--------------------------------
gestatcat1.2
[0. 1.]
--------------------------------
gestatcat2.2
[1. 0.]
--------------------------------
gestatcat3.2
[0. 1.]
--------------------------------
gestatcat4.2
[1. 0.]
--------------------------------
gestatcat5.1
[1. 0.]
--------------------------------
gestatcat6.2
[0. 1.]
--------------------------------
gestatcat7.2
[1. 0.]
--------------------------------
gestatcat8.2
[0. 1.]
--------------------------------
gestatcat5.2
[0. 1.]
--------------------------------
gestatcat9.2
[0. 1.]
--------------------------------
gestatcat10.2
[1. 0.]
--------------------------------
othermr
[1. 0.]
--------------------------------
dmar
[1. 0.]
--------------------------------
csex
[0. 1.]
--------------------------------
cardiac
[0. 1.]
--------------------------------
uterine
[0. 1.]
--------------------------------
lung
[0. 1.]
--------------------------------
diabetes
[0. 1.]
--------------------------------
herpes
[0. 1.]
--------------------------------
anemia
[0. 1.]
--------------------------------
hydra
[0. 1.]
--------------------------------
chyper
[0. 1.]
--------------------------------
phyper
[0. 1.]
--------------------------------
incervix
[0. 1.]
--------------------------------
pre4000
[0. 1.]
--------------------------------
preterm
[0. 1.]
--------------------------------
renal
[0. 1.]
--------------------------------
rh
[0. 1.]
--------------------------------
hemo
[0. 1.]
--------------------------------
tobacco
[0. 1. 2.]
--------------------------------
alcohol
[0. 2. 1.]
--------------------------------
orfath
[0. 6. 1. 5. 4. 3. 2.]
--------------------------------
adequacy
[0. 2. 1.]
--------------------------------
drink5
[0. 5. 1. 3. 2. 4.]
--------------------------------
mpre5
[0. 3. 1. 2.]
--------------------------------
meduc6
[2. 1. 4. 3. 0.]
--------------------------------
mrace
[0. 1. 2. 6. 7. 4. 3. 5. 8.]
--------------------------------
ormoth
[0. 1. 4. 5. 3. 2.]
--------------------------------
frace
[0. 9. 1. 2. 7. 6. 4. 5. 3. 8.]
--------------------------------
birattnd
[0. 4. 1. 2. 3.]
--------------------------------
stoccfipb_reg
[5. 8. 7. 6. 0. 4. 2. 3. 1.]
--------------------------------
mplbir_reg
[5. 7. 1. 6. 4. 2. 8. 3. 0.]
--------------------------------
cigar6
[0. 3. 1. 6. 2. 4. 5.]
--------------------------------
mager8
[2. 5. 4. 3. 1. 6. 0. 7.]
--------------------------------
pldel
[0. 3. 2. 4. 1.]
--------------------------------
brstate_reg
[5. 6. 8. 7. 1. 0. 4. 2. 3.]
--------------------------------
feduc6
[2. 5. 4. 1. 3. 0.]
--------------------------------
dfageq
[1. 8. 0. 6. 7. 3. 2. 4. 5.]
--------------------------------
nprevistq
[0. 1. 3. 2. 4.]
--------------------------------
data_year
[0. 1. 2.]
--------------------------------
crace
[0. 1. 2. 6. 7. 4. 5. 3. 8.]
--------------------------------
birmon
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
--------------------------------
dtotord_min
[ 3.  1.  2.  4.  5.  6.  8.  7.  9. 11. 13. 10. 15. 12. 14. 17.]
--------------------------------
dlivord_min
[ 3.  1.  2.  4.  5.  6.  9.  8. 10.  7. 15. 13. 11. 12.]
--------------------------------
t
[0 1]
--------------------------------
y
[0. 1.]
--------------------------------

In [32]:
base_twins['y'].value_counts()

0.0    9931
1.0    2053
Name: y, dtype: int64