# Extract the LaLonde dataset 

We want to extract the LaLonde data set that has been used to generate all the other realcause datasets in the `realcause_datasets` folder. This is the same base data set that we will use to train the Credence model.

In [27]:
import pandas as pd
import numpy as np
from numpy.testing import assert_approx_equal
from pathlib import Path
import time

from loading import load_from_folder

from data.lalonde import load_lalonde
from data.twins import load_twins
from consts import REALCAUSE_DATASETS_FOLDER, N_SAMPLE_SEEDS, N_AGG_SEEDS
import matplotlib.pyplot as plt

In [4]:
psid_gen_model, args = load_from_folder(dataset='lalonde_psid1')
psid_w, psid_t, psid_y = load_lalonde(obs_version='psid', data_format='pandas')

Namespace(activation='ReLU', atoms=[0.0], batch_size=25000, comet=True, data='lalonde', dataroot='/home/mila/r/raghupas/causal-benchmark/datasets', dim_h=4, dist='SigmoidFlow', dist_args=['ndim=2', 'base_distribution=uniform'], early_stop=True, eval=True, grad_norm=inf, ignore_w=False, kernel_t='RBFKernel', kernel_y='RBFKernel', lr=0.01, model_type='tarnet', n_hidden_layers=1, num_epochs=10000, num_tasks=32, num_univariate_tests=100, overwrite_reload='', patience=None, saveroot='save', seed=123, test_prop=0.4, test_size=None, train=True, train_prop=0.5, val_prop=0.1, var_dist='MeanFieldVariationalDistribution', w_transform='Normalize', y_transform='Normalize')
2024-05-30 20:04:36.186790 / Namespace(activation='ReLU', atoms=[0.0], batch_size=25000, comet=False, data='lalonde', dataroot='./datasets', dim_h=4, dist='SigmoidFlow', dist_args=['ndim=2', 'base_distribution=uniform'], early_stop=True, eval=False, grad_norm=inf, ignore_w=False, kernel_t='RBFKernel', kernel_y='RBFKernel', lr=0.01, model_type='tarnet', n_hidden_layers=1, num_epochs=10000, num_tasks=32, num_univariate_tests=100, overwrite_reload='', patience=None, saveroot='/work/pi_jensen_umass_edu/pboddavarama_umass_edu/nfl/realcause/GenModelCkpts/lalonde/psid1/save', seed=123, test_prop=0.4, test_size=None, train=False, train_prop=0.5, val_prop=0.1, var_dist='MeanFieldVariationalDistribution', w_transform='Normalize', y_transform='Normalize')
2024-05-30 20:04:36.186835 / getting data: lalonde
2024-05-30 20:04:36.199933 / ate: None
2024-05-30 20:04:36.199995 / <models.distributions.distributions.MixedDistribution object at 0x7f56e8362ac0>
2024-05-30 20:04:36.200021 / {'batch_size': 25000, 'lr': 0.01, 'num_epochs': 10000, 'verbose': True, 'print_every_iters': 100, 'optim': <class 'torch.optim.adam.Adam'>, 'eval_every': 100, 'plot_every': 100, 'p_every': 100, 'optim_args': {}}
2024-05-30 20:04:36.200049 / model type: tarnet
2024-05-30 20:04:36.200141 / {'n_hidden_layers': 1, 'dim_h': 4, 'activation': ReLU()}
n_train: 1338	n_val: 268	n_test: 1069
test_idxs:  (1069,)

In [5]:
psid_w

,age,education,black,hispanic,married,nodegree,re74,re75
0,37.0,11.0,1.0,0.0,1.0,1.0,0.000000,0.000000
1,22.0,9.0,0.0,1.0,0.0,1.0,0.000000,0.000000
2,30.0,12.0,1.0,0.0,0.0,0.0,0.000000,0.000000
3,27.0,11.0,1.0,0.0,0.0,1.0,0.000000,0.000000
4,33.0,8.0,1.0,0.0,0.0,1.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...
2485,47.0,8.0,0.0,0.0,1.0,1.0,44667.363281,33837.097656
2486,32.0,8.0,0.0,0.0,1.0,1.0,47022.402344,67137.093750
2487,47.0,10.0,0.0,0.0,1.0,1.0,48197.964844,47968.113281
2488,54.0,0.0,0.0,1.0,1.0,1.0,49228.539062,44220.968750
2489,40.0,8.0,0.0,0.0,1.0,1.0,50940.937500,55500.000000

In [6]:
psid_gen_model.ate(noisy=True)

-13195.036332417525

In [7]:
psid_gen_model.ate(noisy=False)

/work/pi_jensen_umass_edu/pboddavarama_umass_edu/nfl/realcause/models/distributions/distributions.py:275: UserWarning: mean not implemented for <models.distributions.distributions.SigmoidFlow object at 0x7f56e82f11c0> ndim:2 base_distribution:uniform
  warnings.warn(f'mean not implemented for {self.__str__()}')

0.0

In [8]:
psid_gen_model

This is the dataset that has been used to generate the `lalonde_psid` datasets with realcause. We will now store and use this dataset for Credence.

In [13]:
# Store the lalonde psid data set here. 

# Join the psid_w, psid_t, psid_y dataframes into a single dataframe
psid = pd.concat([psid_w, psid_t, psid_y], axis=1)
psid.to_csv('pba_data/psid.csv', index=False)

In [7]:
# Testing the realcause package for basic functionality
from loading import load_realcause_dataset

df = load_realcause_dataset('lalonde_psid', 1)

In [8]:
df

,age,education,black,hispanic,married,nodegree,re74,re75,t,y,y0,y1,ite
0,37.0,11.0,1.0,0.0,1.0,1.0,0.000,0.000,0.0,5532.554,5532.554,0.0000,-5532.554
1,22.0,9.0,0.0,1.0,0.0,1.0,0.000,0.000,0.0,0.000,0.000,4797.9730,4797.973
2,30.0,12.0,1.0,0.0,0.0,0.0,0.000,0.000,0.0,0.000,0.000,0.0000,0.000
3,27.0,11.0,1.0,0.0,0.0,1.0,0.000,0.000,0.0,1667.217,1667.217,0.0000,-1667.217
4,33.0,8.0,1.0,0.0,0.0,1.0,0.000,0.000,0.0,0.000,0.000,3085.3630,3085.363
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2670,47.0,8.0,0.0,0.0,1.0,1.0,44667.363,33837.098,0.0,43386.914,43386.914,6671.3926,-36715.523
2671,32.0,8.0,0.0,0.0,1.0,1.0,47022.402,67137.090,0.0,71678.370,71678.370,0.0000,-71678.370
2672,47.0,10.0,0.0,0.0,1.0,1.0,48197.965,47968.113,0.0,50136.547,50136.547,7171.6323,-42964.914
2673,54.0,0.0,0.0,1.0,1.0,1.0,49228.540,44220.970,0.0,38690.840,38690.840,14053.9480,-24636.890
2674,40.0,8.0,0.0,0.0,1.0,1.0,50940.938,55500.000,0.0,59296.164,59296.164,6996.2440,-52299.920

In [9]:
df.shape

(2675, 13)

In [10]:
df.columns

Index(['age', 'education', 'black', 'hispanic', 'married', 'nodegree', 're74',
       're75', 't', 'y', 'y0', 'y1', 'ite'],
      dtype='object')

In [2]:
# Extract the twins dataset 
d = load_twins(dataroot='datasets')

Twins dataset already exists at datasets/twins.csv

In [7]:
df = pd.read_csv('datasets/twins.csv', index_col=0)

In [8]:
df.head()

,eclamp,gestatcat1,gestatcat2,gestatcat3,gestatcat4,gestatcat5,gestatcat6,gestatcat7,gestatcat8,gestatcat9,...,crace,birmon,dtotord_min,dlivord_min,T,y0,y1,yf,y_cf,Propensity
0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,3.0,3.0,0,0.0,0.0,0.0,0.0,0.638284
1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,1,0.0,1.0,1.0,0.0,0.587705
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0,0.0,0.0,0.0,0.0,0.802878
3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,2.0,2.0,1,0.0,0.0,0.0,0.0,0.741004
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,3.0,1,0.0,0.0,0.0,0.0,0.616016

In [11]:
# Base dataset for twins.csv
base_twins = pd.read_csv('base_datasets/twins.csv')

In [12]:
base_twins.head()

,eclamp,gestatcat1,gestatcat2,gestatcat3,gestatcat4,gestatcat5,gestatcat6,gestatcat7,gestatcat8,gestatcat9,...,feduc6,dfageq,nprevistq,data_year,crace,birmon,dtotord_min,dlivord_min,t,y
0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,3.0,3.0,0,0.0
1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,5.0,8.0,0.0,0.0,0.0,0.0,1.0,1.0,1,1.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,4.0,6.0,0.0,0.0,0.0,0.0,2.0,2.0,1,0.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,7.0,0.0,0.0,1.0,0.0,3.0,3.0,1,0.0

In [20]:
# Find the proportion of t = 0 and t = 1 in the base dataset
base_twins['t'].value_counts() / len(base_twins)

1    0.745661
0    0.254339
Name: t, dtype: float64

In [21]:
# See which columns are in the twins dataset which are continuous and which are categorical
base_twins.dtypes

eclamp         float64
gestatcat1     float64
gestatcat2     float64
gestatcat3     float64
gestatcat4     float64
                ...
birmon         float64
dtotord_min    float64
dlivord_min    float64
t                int64
y              float64
Length: 77, dtype: object

In [22]:
for col in base_twins.columns:
    print(col)
    print(base_twins[col].unique())
    print('--------------------------------')

eclamp
[0. 1.]
--------------------------------
gestatcat1
[0. 1.]
--------------------------------
gestatcat2
[1. 0.]
--------------------------------
gestatcat3
[1. 0.]
--------------------------------
gestatcat4
[0. 1.]
--------------------------------
gestatcat5
[1. 0.]
--------------------------------
gestatcat6
[1. 0.]
--------------------------------
gestatcat7
[0. 1.]
--------------------------------
gestatcat8
[0. 1.]
--------------------------------
gestatcat9
[1. 0.]
--------------------------------
gestatcat10
[0. 1.]
--------------------------------
gestatcat1.1
[0. 1.]
--------------------------------
gestatcat2.1
[1. 0.]
--------------------------------
gestatcat3.1
[1. 0.]
--------------------------------
bord
[1. 0.]
--------------------------------
gestatcat4.1
[1. 0.]
--------------------------------
gestatcat6.1
[1. 0.]
--------------------------------
gestatcat7.1
[1. 0.]
--------------------------------
gestatcat8.1
[1. 0.]
--------------------------------
gestatcat9.1
[0. 1.]
--------------------------------
gestatcat10.1
[0. 1.]
--------------------------------
gestatcat1.2
[0. 1.]
--------------------------------
gestatcat2.2
[1. 0.]
--------------------------------
gestatcat3.2
[0. 1.]
--------------------------------
gestatcat4.2
[1. 0.]
--------------------------------
gestatcat5.1
[1. 0.]
--------------------------------
gestatcat6.2
[0. 1.]
--------------------------------
gestatcat7.2
[1. 0.]
--------------------------------
gestatcat8.2
[0. 1.]
--------------------------------
gestatcat5.2
[0. 1.]
--------------------------------
gestatcat9.2
[0. 1.]
--------------------------------
gestatcat10.2
[1. 0.]
--------------------------------
othermr
[1. 0.]
--------------------------------
dmar
[1. 0.]
--------------------------------
csex
[0. 1.]
--------------------------------
cardiac
[0. 1.]
--------------------------------
uterine
[0. 1.]
--------------------------------
lung
[0. 1.]
--------------------------------
diabetes
[0. 1.]
--------------------------------
herpes
[0. 1.]
--------------------------------
anemia
[0. 1.]
--------------------------------
hydra
[0. 1.]
--------------------------------
chyper
[0. 1.]
--------------------------------
phyper
[0. 1.]
--------------------------------
incervix
[0. 1.]
--------------------------------
pre4000
[0. 1.]
--------------------------------
preterm
[0. 1.]
--------------------------------
renal
[0. 1.]
--------------------------------
rh
[0. 1.]
--------------------------------
hemo
[0. 1.]
--------------------------------
tobacco
[0. 1. 2.]
--------------------------------
alcohol
[0. 2. 1.]
--------------------------------
orfath
[0. 6. 1. 5. 4. 3. 2.]
--------------------------------
adequacy
[0. 2. 1.]
--------------------------------
drink5
[0. 5. 1. 3. 2. 4.]
--------------------------------
mpre5
[0. 3. 1. 2.]
--------------------------------
meduc6
[2. 1. 4. 3. 0.]
--------------------------------
mrace
[0. 1. 2. 6. 7. 4. 3. 5. 8.]
--------------------------------
ormoth
[0. 1. 4. 5. 3. 2.]
--------------------------------
frace
[0. 9. 1. 2. 7. 6. 4. 5. 3. 8.]
--------------------------------
birattnd
[0. 4. 1. 2. 3.]
--------------------------------
stoccfipb_reg
[5. 8. 7. 6. 0. 4. 2. 3. 1.]
--------------------------------
mplbir_reg
[5. 7. 1. 6. 4. 2. 8. 3. 0.]
--------------------------------
cigar6
[0. 3. 1. 6. 2. 4. 5.]
--------------------------------
mager8
[2. 5. 4. 3. 1. 6. 0. 7.]
--------------------------------
pldel
[0. 3. 2. 4. 1.]
--------------------------------
brstate_reg
[5. 6. 8. 7. 1. 0. 4. 2. 3.]
--------------------------------
feduc6
[2. 5. 4. 1. 3. 0.]
--------------------------------
dfageq
[1. 8. 0. 6. 7. 3. 2. 4. 5.]
--------------------------------
nprevistq
[0. 1. 3. 2. 4.]
--------------------------------
data_year
[0. 1. 2.]
--------------------------------
crace
[0. 1. 2. 6. 7. 4. 5. 3. 8.]
--------------------------------
birmon
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
--------------------------------
dtotord_min
[ 3.  1.  2.  4.  5.  6.  8.  7.  9. 11. 13. 10. 15. 12. 14. 17.]
--------------------------------
dlivord_min
[ 3.  1.  2.  4.  5.  6.  9.  8. 10.  7. 15. 13. 11. 12.]
--------------------------------
t
[0 1]
--------------------------------
y
[0. 1.]
--------------------------------

In [32]:
base_twins['y'].value_counts()

0.0    9931
1.0    2053
Name: y, dtype: int64